// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCept1Li514_DYKoyMkqhU479CaBUbCddo',
    appId: '1:243158214975:web:5bc898ae015951fd210b8a',
    messagingSenderId: '243158214975',
    projectId: 'zaidapp-db834',
    authDomain: 'zaidapp-db834.firebaseapp.com',
    storageBucket: 'zaidapp-db834.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpQvgVSiIavKy9kICP3DqdGYBVZKJcxcM',
    appId: '1:243158214975:android:67e9216a053098dc210b8a',
    messagingSenderId: '243158214975',
    projectId: 'zaidapp-db834',
    storageBucket: 'zaidapp-db834.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv_f_R7PzLYiJl_Yax61KgQs44D-DThTY',
    appId: '1:243158214975:ios:9ae214dcff1d8263210b8a',
    messagingSenderId: '243158214975',
    projectId: 'zaidapp-db834',
    storageBucket: 'zaidapp-db834.appspot.com',
    iosClientId: '243158214975-be1io52huu1k145trnck1qvno19n3p1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
